services:
  musync:
    image: musync
    build:
      context: .
      dockerfile: src/Musync/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      Database__Provider: "Postgres"
      ConnectionStrings__Postgres: "Host=postgres;Database=musync;Username=musync;Password=musync"
